# Generated by Django 2.1.7 on 2019-06-04 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('detail_body', models.CharField(default='#ffffff', max_length=7)),
                ('detail_buttons', models.CharField(default='#ffffff', max_length=7)),
                ('detail_sleeve', models.CharField(default='#ffffff', max_length=7)),
                ('detail_banding', models.CharField(default='#ffffff', max_length=7)),
                ('detail_stripes', models.CharField(default='#ffffff', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('MJ', 'Major'), ('CL', 'Club'), ('UR', 'User')], default='MJ', max_length=2)),
                ('group_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(to='homepage.Group')),
                ('recent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Design')),
                ('user_group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='homepage.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='master',
            field=models.ManyToManyField(related_name='master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='design',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Group'),
        ),
        migrations.AddField(
            model_name='design',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='design',
            name='who',
            field=models.ManyToManyField(blank=True, related_name='who', to=settings.AUTH_USER_MODEL),
        ),
    ]
