# Generated by Django 2.2.1 on 2019-06-15 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('body', models.CharField(default='#001c58', max_length=7)),
                ('button', models.CharField(default='#fcfcfc', max_length=7)),
                ('sleeve', models.CharField(default='#fcfcfc', max_length=7)),
                ('banding', models.CharField(default='#001c58', max_length=7)),
                ('stripe', models.CharField(default='#fcfcfc', max_length=7)),
                ('front_image_url', models.CharField(max_length=100, null=True)),
                ('back_image_url', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('MJ', 'Major'), ('CL', 'Club'), ('UR', 'User')], default='MJ', max_length=2)),
                ('group_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ManyToManyField(related_name='master', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textvalue', models.CharField(max_length=50)),
                ('fontFamily', models.CharField(max_length=50)),
                ('fill', models.CharField(max_length=50)),
                ('fontStyle', models.CharField(max_length=50)),
                ('fontSize', models.IntegerField(default=100)),
                ('left', models.IntegerField(default=0)),
                ('top', models.IntegerField(default=0)),
                ('stroke', models.CharField(default='#fcfcfc', max_length=7)),
                ('strokewidth', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(to='homepage.Group')),
                ('recent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Design')),
                ('user_group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='homepage.Group')),
            ],
        ),
        migrations.AddField(
            model_name='design',
            name='front_chest_text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_chest', to='homepage.Text'),
        ),
        migrations.AddField(
            model_name='design',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Group'),
        ),
        migrations.AddField(
            model_name='design',
            name='lower_back_text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower_back', to='homepage.Text'),
        ),
        migrations.AddField(
            model_name='design',
            name='middle_back_text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='middle_back', to='homepage.Text'),
        ),
        migrations.AddField(
            model_name='design',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='design',
            name='right_arm_text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_arm', to='homepage.Text'),
        ),
        migrations.AddField(
            model_name='design',
            name='upper_back_text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upper_back', to='homepage.Text'),
        ),
        migrations.AddField(
            model_name='design',
            name='who',
            field=models.ManyToManyField(blank=True, related_name='who', to=settings.AUTH_USER_MODEL),
        ),
    ]
