# Generated by Django 2.2.1 on 2019-06-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.CharField(max_length=50)),
                ('font_family', models.CharField(max_length=50)),
                ('font_fill', models.CharField(max_length=50)),
                ('font_style', models.CharField(max_length=50)),
                ('font_size', models.IntegerField(default=100)),
            ],
        ),
        migrations.AlterField(
            model_name='design',
            name='detail_banding',
            field=models.CharField(default='#001c58', max_length=7),
        ),
        migrations.AlterField(
            model_name='design',
            name='detail_body',
            field=models.CharField(default='#001c58', max_length=7),
        ),
        migrations.AlterField(
            model_name='design',
            name='detail_buttons',
            field=models.CharField(default='#fcfcfc', max_length=7),
        ),
        migrations.AlterField(
            model_name='design',
            name='detail_sleeve',
            field=models.CharField(default='#fcfcfc', max_length=7),
        ),
        migrations.AlterField(
            model_name='design',
            name='detail_stripes',
            field=models.CharField(default='#fcfcfc', max_length=7),
        ),
        migrations.AddField(
            model_name='design',
            name='front_chest',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_chest', to='homepage.Text'),
        ),
        migrations.AddField(
            model_name='design',
            name='left_arm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_arm', to='homepage.Text'),
        ),
        migrations.AddField(
            model_name='design',
            name='lower_back',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower_back', to='homepage.Text'),
        ),
        migrations.AddField(
            model_name='design',
            name='middle_back',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='middle_back', to='homepage.Text'),
        ),
        migrations.AddField(
            model_name='design',
            name='right_arm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_arm', to='homepage.Text'),
        ),
        migrations.AddField(
            model_name='design',
            name='upper_back',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upper_back', to='homepage.Text'),
        ),
    ]
