# Generated by Django 2.1.7 on 2019-06-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='detail_banding',
            field=models.CharField(default='#001c58', max_length=7),
        ),
        migrations.AlterField(
            model_name='design',
            name='detail_body',
            field=models.CharField(default='#001c58', max_length=7),
        ),
        migrations.AlterField(
            model_name='design',
            name='detail_buttons',
            field=models.CharField(default='#fcfcfc', max_length=7),
        ),
        migrations.AlterField(
            model_name='design',
            name='detail_sleeve',
            field=models.CharField(default='#fcfcfc', max_length=7),
        ),
        migrations.AlterField(
            model_name='design',
            name='detail_stripes',
            field=models.CharField(default='#fcfcfc', max_length=7),
        ),
    ]
