# Generated by Django 2.2.1 on 2019-06-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190606_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='front_chest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_chest', to='homepage.Text'),
        ),
        migrations.AlterField(
            model_name='design',
            name='left_arm',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_arm', to='homepage.Text'),
        ),
        migrations.AlterField(
            model_name='design',
            name='lower_back',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower_back', to='homepage.Text'),
        ),
        migrations.AlterField(
            model_name='design',
            name='middle_back',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='middle_back', to='homepage.Text'),
        ),
        migrations.AlterField(
            model_name='design',
            name='right_arm',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_arm', to='homepage.Text'),
        ),
        migrations.AlterField(
            model_name='design',
            name='upper_back',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upper_back', to='homepage.Text'),
        ),
    ]
