# Generated by Django 2.2.1 on 2019-06-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190606_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='front_chest',
            new_name='front_chest_text',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='left_arm',
            new_name='left_arm_text',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='lower_back',
            new_name='lower_back_text',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='middle_back',
            new_name='middle_back_text',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='right_arm',
            new_name='right_arm_text',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='upper_back',
            new_name='upper_back_text',
        ),
    ]
