# Generated by Django 2.2.1 on 2019-06-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20190615_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='detail_banding',
            new_name='banding',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='detail_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='detail_buttons',
            new_name='button',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='detail_sleeve',
            new_name='sleeve',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='detail_stripes',
            new_name='stripe',
        ),
    ]
