# Generated by Django 2.2.1 on 2019-06-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20190615_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='stroke',
            field=models.CharField(default='#fcfcfc', max_length=7),
        ),
        migrations.AddField(
            model_name='text',
            name='strokewidth',
            field=models.IntegerField(default=0),
        ),
    ]
