# Generated by Django 2.2.1 on 2019-05-11 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master', to=settings.AUTH_USER_MODEL),
        ),
    ]
