# Generated by Django 2.2.1 on 2019-05-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_group_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Design'),
        ),
    ]
