# Generated by Django 2.2.1 on 2019-05-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_profile_recent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Design'),
        ),
    ]
