# Generated by Django 2.2.1 on 2019-05-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20190511_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('MJ', 'Major'), ('CL', 'Club'), ('UR', 'User')], default='MJ', max_length=2),
        ),
    ]
