# Generated by Django 2.2.1 on 2019-05-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20190511_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Group'),
        ),
    ]
