# Generated by Django 2.2.1 on 2019-05-11 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0015_profile_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='master',
        ),
        migrations.AddField(
            model_name='group',
            name='master',
            field=models.ManyToManyField(related_name='master', to=settings.AUTH_USER_MODEL),
        ),
    ]
